# Generated by Django 4.2.16 on 2025-05-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_alter_estoque_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoqueimei',
            options={'permissions': (('can_view_all_imei', 'Pode visualizar todos os IMEI'),), 'verbose_name': 'Estoque IMEI', 'verbose_name_plural': 'Estoques IMEI'},
        ),
    ]
