# Generated by Django 4.2.16 on 2025-05-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_alter_entradaestoque_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaestoque',
            name='data_entrada',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque', to='estoque.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
