# Generated by Django 4.2.16 on 2025-05-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0023_alter_entradaestoque_data_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoentrada',
            name='venda_unitaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Venda Unitária'),
        ),
    ]
