# Generated by Django 4.2.16 on 2025-05-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_alter_produtoentrada_venda_unitaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueimei',
            name='data_venda',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Venda'),
        ),
    ]
