# Generated by Django 4.2.16 on 2025-05-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0025_estoqueimei_data_venda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoentrada',
            options={'ordering': ['entrada__data_entrada'], 'verbose_name': 'Produto na Entrada de Estoque', 'verbose_name_plural': 'Produtos na Entrada de Estoque'},
        ),
    ]
