# Generated by Django 4.2.16 on 2025-05-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0026_alter_produtoentrada_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaestoque',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada'),
        ),
    ]
