# Generated by Django 4.2.16 on 2025-05-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0027_alter_entradaestoque_data_entrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradaestoque',
            options={'ordering': ['-data_entrada'], 'verbose_name': 'Entrada de Estoque', 'verbose_name_plural': 'Entradas de Estoque'},
        ),
        migrations.AddField(
            model_name='estoqueimei',
            name='aplicativo_instalado',
            field=models.BooleanField(default=False, verbose_name='Aplicativo Instalado'),
        ),
    ]
