# Generated by Django 4.2.16 on 2025-05-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0028_alter_entradaestoque_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaestoque',
            name='venda_liberada',
            field=models.BooleanField(default=False, verbose_name='Liberada para Venda'),
        ),
    ]
