# Generated by Django 4.2.16 on 2025-05-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0029_entradaestoque_venda_liberada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradaestoque',
            options={'ordering': ['-data_entrada'], 'permissions': (('can_liberar_venda', 'Pode liberar venda'),), 'verbose_name': 'Entrada de Estoque', 'verbose_name_plural': 'Entradas de Estoque'},
        ),
    ]
