# Generated by Django 4.2.16 on 2025-06-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0030_alter_entradaestoque_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoentrada',
            name='custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Unitário'),
        ),
    ]
