# Generated by Django 4.2.16 on 2025-07-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0031_alter_produtoentrada_custo_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueimei',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
    ]
