# Generated by Django 4.2.16 on 2025-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0032_estoqueimei_cancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaestoque',
            name='numero_nota',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número da Nota'),
        ),
    ]
