# Generated by Django 4.2.16 on 2025-08-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_produto_valor_8_vezes'),
        ('vendas', '0114_analisecreditocliente_imei_informado'),
        ('estoque', '0033_auto_numero_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoqueimei',
            options={'permissions': (('can_view_all_renavam', 'Pode visualizar todos os RENAVAM'),), 'verbose_name': 'Estoque RENAVAM', 'verbose_name_plural': 'Estoques RENAVAM'},
        ),
        migrations.AlterUniqueTogether(
            name='estoqueimei',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='produtoentrada',
            name='imei',
        ),
        migrations.AddField(
            model_name='estoqueimei',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa'),
        ),
        migrations.AddField(
            model_name='estoqueimei',
            name='renavam',
            field=models.CharField(default=123, max_length=20, verbose_name='RENAVAM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtoentrada',
            name='renavam',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RENAVAM'),
        ),
        migrations.AlterUniqueTogether(
            name='estoqueimei',
            unique_together={('renavam', 'produto', 'loja')},
        ),
        migrations.RemoveField(
            model_name='estoqueimei',
            name='imei',
        ),
    ]
