# Generated by Django 4.2.16 on 2025-04-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_tipoproduto_assistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='entrada_cliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_4_vezes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_6_vezes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_repasse_logista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
