# Generated by Django 4.2.16 on 2025-05-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_produto_entrada_cliente_produto_valor_4_vezes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='memoria',
        ),
    ]
