# Generated by Django 4.2.16 on 2025-05-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_alter_corproduto_criado_por_alter_corproduto_loja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_8_vezes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
