# Generated by Django 4.2.16 on 2025-08-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_produto_valor_8_vezes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='valor_4_vezes',
            new_name='valor_10_vezes',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='valor_6_vezes',
            new_name='valor_12_vezes',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='valor_8_vezes',
            new_name='valor_14_vezes',
        ),
    ]
