# Generated by Django 4.2.16 on 2025-09-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_rename_valor_4_vezes_produto_valor_10_vezes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fabricante',
        ),
    ]
