# Generated by Django 4.2.16 on 2025-09-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_remove_fabricante_from_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_4_vezes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_6_vezes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_8_vezes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
