# Generated by Django 4.2.16 on 2025-11-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_add_parcelamento_4x_6x_8x'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_16_vezes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
