# Generated by Django 4.2.16 on 2026-03-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0023_produto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor base'),
        ),
    ]
