# Generated by Django 4.2.16 on 2025-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0042_remove_cliente_cliente_cred_facil_loja_chave_pix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='data_aprovacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisecreditocliente',
            name='data_reprovacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='data_analise',
            field=models.DateField(auto_now_add=True),
        ),
    ]
