# Generated by Django 4.2.16 on 2025-04-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0044_alter_analisecreditocliente_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('can_more_desconto', 'Pode dar mais desconto'), ('can_generate_report_sale', 'Pode gerar relatório de vendas'), ('change_status_analise', 'Pode alterar status de análise')), 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AddField(
            model_name='analisecreditocliente',
            name='data_cancelamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='status',
            field=models.CharField(choices=[('EA', 'Em análise'), ('A', 'Aprovado'), ('R', 'Reprovado'), ('C', 'Cancelado')], default='EA', max_length=20),
        ),
    ]
