# Generated by Django 4.2.16 on 2025-04-21 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0045_alter_venda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analises_credito_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
