# Generated by Django 4.2.16 on 2025-04-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0046_analisecreditocliente_aprovado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='data_analise',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='data_reprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
