# Generated by Django 4.2.16 on 2025-04-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0048_alter_cliente_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='numero_parcelas',
            field=models.CharField(blank=True, choices=[('4', '4x'), ('6', '6x')], max_length=20, null=True),
        ),
    ]
