# Generated by Django 4.2.16 on 2025-04-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_alter_estoque_produto'),
        ('vendas', '0049_analisecreditocliente_numero_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='imei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analises_credito_imei', to='estoque.estoqueimei'),
        ),
        migrations.AddField(
            model_name='comprovantescliente',
            name='comprovante_residencia_analise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comprovantescliente',
            name='consulta_serasa_analise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comprovantescliente',
            name='documento_identificacao_frente_analise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comprovantescliente',
            name='documento_identificacao_verso_analise',
            field=models.BooleanField(default=False),
        ),
    ]
