# Generated by Django 4.2.16 on 2025-04-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0050_analisecreditocliente_imei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovantescliente',
            name='consulta_serasa',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes_clientes/%Y/%m/%d/'),
        ),
    ]
