# Generated by Django 4.2.16 on 2025-04-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0051_alter_comprovantescliente_consulta_serasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='tipo_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_tipo_entrega', to='vendas.tipoentrega'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='tipo_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_tipo_venda', to='vendas.tipovenda'),
        ),
    ]
