# Generated by Django 4.2.16 on 2025-05-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0052_alter_venda_tipo_entrega_alter_venda_tipo_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovenda',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='tipovenda',
            name='loja',
        ),
        migrations.RemoveField(
            model_name='tipovenda',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='tipo_entrega',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='tipo_venda',
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='comprovante_residencia',
            field=models.ImageField(upload_to='comprovantes_clientes'),
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='consulta_serasa',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes_clientes'),
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='documento_identificacao_frente',
            field=models.ImageField(upload_to='comprovantes_clientes'),
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='documento_identificacao_verso',
            field=models.ImageField(upload_to='comprovantes_clientes'),
        ),
        migrations.DeleteModel(
            name='TipoEntrega',
        ),
        migrations.DeleteModel(
            name='TipoVenda',
        ),
    ]
