# Generated by Django 4.2.16 on 2025-05-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0058_alter_venda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisecreditocliente',
            options={'permissions': (('can_approve_credit_analysis', 'Pode aprovar análise de crédito'), ('can_reject_credit_analysis', 'Pode reprovar análise de crédito'), ('can_cancel_credit_analysis', 'Pode cancelar análise de crédito'), ('view_all_analise_credito', 'Pode ver todos as análise de crédito')), 'verbose_name_plural': 'Análises de Crédito'},
        ),
    ]
