# Generated by Django 4.2.16 on 2025-05-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0059_alter_analisecreditocliente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='data_pagamento',
            field=models.CharField(blank=True, choices=[('1', 'Dia 1'), ('10', 'Dia 10'), ('20', 'Dia 20')], max_length=20, null=True),
        ),
    ]
