# Generated by Django 4.2.16 on 2025-05-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0060_analisecreditocliente_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='data_pagamento',
            field=models.CharField(blank=True, choices=[('1', 'Dia 1'), ('10', 'Dia 10'), ('20', 'Dia 20')], max_length=20, null=True, verbose_name='Data de pagamento'),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='numero_parcelas',
            field=models.CharField(choices=[('4', '4x'), ('6', '6x')], default='1', max_length=20),
            preserve_default=False,
        ),
    ]
