# Generated by Django 4.2.16 on 2025-05-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0061_alter_analisecreditocliente_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analises_credito_venda', to='vendas.venda'),
        ),
    ]
