# Generated by Django 4.2.16 on 2025-05-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_alter_estoque_produto'),
        ('vendas', '0062_analisecreditocliente_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='imei',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='analises_credito_imei', to='estoque.estoqueimei'),
            preserve_default=False,
        ),
    ]
