# Generated by Django 4.2.16 on 2025-05-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0064_analisecreditocliente_venda_gerada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisecreditocliente',
            name='venda_gerada',
        ),
    ]
