# Generated by Django 4.2.16 on 2025-05-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0065_remove_analisecreditocliente_venda_gerada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'permissions': (('can_view_all_payments', 'Pode ver todos os pagamentos'),), 'verbose_name_plural': 'Pagamentos'},
        ),
    ]
