# Generated by Django 4.2.16 on 2025-05-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_alter_estoque_produto'),
        ('vendas', '0066_alter_pagamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='imei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analises_credito_imei', to='estoque.estoqueimei'),
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='documento_identificacao_frente_analise',
            field=models.BooleanField(default=True),
        ),
    ]
