# Generated by Django 4.2.16 on 2025-05-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0067_alter_analisecreditocliente_imei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovantescliente',
            name='documento_identificacao_frente_analise',
            field=models.BooleanField(default=False),
        ),
    ]
