# Generated by Django 4.2.16 on 2025-05-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0068_alter_comprovantescliente_documento_identificacao_frente_analise'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='repasse_logista',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
