# Generated by Django 4.2.16 on 2025-05-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0069_venda_repasse_logista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('can_more_desconto', 'Pode dar mais desconto'), ('can_generate_report_sale', 'Pode gerar relatório de vendas'), ('change_status_analise', 'Pode alterar status de análise'), ('can_view_all_sales', 'Pode ver todas as vendas'), ('can_view_produtos_vendidos', 'Pode ver aba produtos vendidos'), ('can_edit_finished_sale', 'Pode editar venda finalizada')), 'verbose_name_plural': 'Vendas'},
        ),
    ]
