# Generated by Django 4.2.16 on 2025-05-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0070_alter_venda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtovenda',
            options={'ordering': ['-id'], 'permissions': (('can_view_all_products_sold', 'Pode ver todos os produtos vendidos'),), 'verbose_name_plural': 'Produtos Vendas'},
        ),
        migrations.AddField(
            model_name='parcela',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
