# Generated by Django 4.2.16 on 2025-05-04 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0072_alter_cliente_comprovantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comprovantes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='vendas.comprovantescliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato_adicional',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='vendas.contatoadicional'),
        ),
    ]
