# Generated by Django 4.2.16 on 2025-05-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0073_alter_cliente_comprovantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovantescliente',
            name='comprovante_residencia',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_clientes'),
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='consulta_serasa',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_clientes'),
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='documento_identificacao_frente',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_clientes'),
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='documento_identificacao_verso',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_clientes'),
        ),
    ]
