# Generated by Django 4.2.16 on 2025-05-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0075_informacoespessoais'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='informacoes_pessoais',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='vendas.informacoespessoais'),
        ),
    ]
