# Generated by Django 4.2.16 on 2025-05-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0076_cliente_informacoes_pessoais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='informacoes_pessoais',
        ),
    ]
