# Generated by Django 4.2.16 on 2025-05-06 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0077_remove_cliente_informacoes_pessoais'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformacoesPessoais',
            new_name='InformacaoPessoal',
        ),
    ]
