# Generated by Django 4.2.16 on 2025-05-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0078_rename_informacoespessoais_informacaopessoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='informacao_pessoal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='vendas.informacaopessoal'),
        ),
    ]
