# Generated by Django 4.2.16 on 2025-05-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0079_cliente_informacao_pessoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_credito_venda', to='vendas.venda'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='vendas.venda'),
        ),
        migrations.AlterField(
            model_name='produtovenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='vendas.venda'),
        ),
    ]
