# Generated by Django 4.2.16 on 2025-05-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0081_alter_analisecreditocliente_aprovado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loja',
            options={'permissions': (('can_view_all_stores', 'Pode ver todas as lojas'),), 'verbose_name_plural': 'Lojas'},
        ),
    ]
