# Generated by Django 4.2.16 on 2025-05-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0083_pagamento_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='pagamento_efetuado',
            field=models.BooleanField(default=False),
        ),
    ]
