# Generated by Django 4.2.16 on 2025-05-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0084_parcela_pagamento_efetuado'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='pagamento_efetuado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
