# Generated by Django 4.2.16 on 2025-05-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0085_parcela_pagamento_efetuado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='credfacil',
            field=models.BooleanField(default=False),
        ),
    ]
