# Generated by Django 4.2.16 on 2025-05-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0086_loja_credfacil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='numero_parcelas',
            field=models.CharField(choices=[('4', '4x'), ('6', '6x'), ('8', '8x')], max_length=20),
        ),
    ]
