# Generated by Django 4.2.16 on 2025-05-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0087_alter_analisecreditocliente_numero_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='porcentagem_desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
