# Generated by Django 4.2.16 on 2025-05-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0088_loja_porcentagem_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='porcentagem_desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
