# Generated by Django 4.2.16 on 2025-05-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0089_pagamento_porcentagem_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='porcentagem_desconto',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
    ]
