# Generated by Django 4.2.16 on 2025-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0091_alter_venda_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='status_aplicativo',
            field=models.CharField(blank=True, choices=[('P', 'Pendente'), ('CP', 'Confirmação pendente'), ('I', 'Instalado')], max_length=20, null=True, verbose_name='Status do aplicativo'),
        ),
    ]
