# Generated by Django 4.2.16 on 2025-05-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0093_alter_analisecreditocliente_status_aplicativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='codigo_aplicativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='qr_code_aplicativo',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes_aplicativo/'),
        ),
    ]
