# Generated by Django 4.2.16 on 2025-05-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0095_alter_analisecreditocliente_status_aplicativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='status_aplicativo',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmação pendente'), ('I', 'Instalado')], default='P', max_length=20, verbose_name='Status do aplicativo'),
        ),
    ]
