# Generated by Django 4.2.16 on 2025-05-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0096_alter_analisecreditocliente_status_aplicativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={'ordering': ['-data_abertura'], 'verbose_name_plural': 'Caixas'},
        ),
    ]
