# Generated by Django 4.2.16 on 2025-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0097_alter_caixa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatoadicional',
            name='obteve_contato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informacaopessoal',
            name='obteve_contato',
            field=models.BooleanField(default=False),
        ),
    ]
