# Generated by Django 4.2.16 on 2025-05-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0098_contatoadicional_obteve_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovantescliente',
            name='restricao',
            field=models.BooleanField(default=False),
        ),
    ]
