# Generated by Django 4.2.16 on 2025-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0101_alter_comprovantescliente_restricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovantescliente',
            name='foto_cliente',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_clientes'),
        ),
    ]
