# Generated by Django 4.2.16 on 2025-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0102_comprovantescliente_foto_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='porcentagem_desconto_4',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loja',
            name='porcentagem_desconto_6',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loja',
            name='porcentagem_desconto_8',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
    ]
