# Generated by Django 4.2.16 on 2025-06-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0104_remove_loja_porcentagem_desconto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'permissions': (('can_view_all_payments', 'Pode ver todos os pagamentos'), ('can_genarate_report_payments', 'Pode gerar relatório de pagamentos')), 'verbose_name_plural': 'Pagamentos'},
        ),
    ]
