# Generated by Django 4.2.16 on 2025-06-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0105_alter_pagamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='repasse_logista',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10),
            preserve_default=False,
        ),
    ]
