# Generated by Django 4.2.16 on 2025-06-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0106_alter_venda_repasse_logista'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='is_trocado',
            field=models.BooleanField(default=False),
        ),
    ]
