# Generated by Django 4.2.16 on 2025-08-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0109_alter_contato_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='desativado',
            field=models.BooleanField(default=False),
        ),
    ]
