# Generated by Django 4.2.16 on 2025-08-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0110_pagamento_desativado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='quitado',
            field=models.BooleanField(default=False),
        ),
    ]
