# Generated by Django 4.2.16 on 2025-08-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0111_pagamento_quitado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'permissions': (('can_view_all_payments', 'Pode ver todos os pagamentos'), ('can_genarate_report_payments', 'Pode gerar relatório de pagamentos'), ('can_confirm_quitacao', 'Pode confirmar quitação de pagamentos')), 'verbose_name_plural': 'Pagamentos'},
        ),
    ]
