# Generated by Django 4.2.16 on 2025-08-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0112_alter_pagamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcela',
            options={'permissions': (('change_vencimento_parcela', 'Pode alterar data de vencimento de parcelas'),), 'verbose_name_plural': 'Parcelas'},
        ),
    ]
