# Generated by Django 4.2.16 on 2025-08-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0113_alter_parcela_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='imei_informado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI Informado'),
        ),
    ]
