# Generated by Django 4.2.16 on 2025-08-31 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0034_alter_estoqueimei_options_and_more'),
        ('vendas', '0114_analisecreditocliente_imei_informado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtovenda',
            old_name='imei',
            new_name='renavam',
        ),
        migrations.RemoveField(
            model_name='analisecreditocliente',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='analisecreditocliente',
            name='imei_informado',
        ),
        migrations.AddField(
            model_name='analisecreditocliente',
            name='renavam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_credito_renavam', to='estoque.estoqueimei', verbose_name='RENAVAM'),
        ),
        migrations.AddField(
            model_name='analisecreditocliente',
            name='renavam_informado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RENAVAM Informado'),
        ),
    ]
