# Generated by Django 4.2.16 on 2025-08-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0115_rename_imei_produtovenda_renavam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='porcentagem_desconto_4',
            new_name='porcentagem_desconto_10',
        ),
        migrations.RenameField(
            model_name='loja',
            old_name='porcentagem_desconto_6',
            new_name='porcentagem_desconto_12',
        ),
        migrations.RenameField(
            model_name='loja',
            old_name='porcentagem_desconto_8',
            new_name='porcentagem_desconto_14',
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='numero_parcelas',
            field=models.CharField(choices=[('10', '10x'), ('12', '12x'), ('14', '14x')], max_length=20),
        ),
    ]
