# Generated by Django 4.2.16 on 2025-08-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0116_rename_porcentagem_desconto_4_loja_porcentagem_desconto_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovantescliente',
            name='foto_cnh',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_clientes', verbose_name='Foto da CNH'),
        ),
        migrations.AddField(
            model_name='comprovantescliente',
            name='foto_cnh_analise',
            field=models.BooleanField(default=False, verbose_name='Análise da Foto da CNH'),
        ),
    ]
