# Generated by Django 4.2.16 on 2025-08-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0117_comprovantescliente_foto_cnh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo'),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='status_aplicativo',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aguardando RENAVAM e Placa'), ('L', 'Liberado para Venda')], default='P', max_length=20, verbose_name='Status do aplicativo'),
        ),
    ]
