# Generated by Django 4.2.16 on 2025-09-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0118_add_placa_veiculo_to_analise_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='data_pagamento',
            field=models.CharField(blank=True, choices=[('5', 'Dia 5'), ('15', 'Dia 15')], max_length=20, null=True, verbose_name='Data de pagamento'),
        ),
    ]
