# Generated by Django 4.2.16 on 2025-09-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0119_update_due_dates_to_05_15'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='porcentagem_desconto_4',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loja',
            name='porcentagem_desconto_6',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loja',
            name='porcentagem_desconto_8',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='numero_parcelas',
            field=models.CharField(choices=[('4', '4x'), ('6', '6x'), ('8', '8x'), ('10', '10x'), ('12', '12x'), ('14', '14x')], max_length=20),
        ),
    ]
