# Generated by Django 4.2.16 on 2025-09-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0120_add_porcentagem_desconto_4x_6x_8x'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprovantescliente',
            options={'permissions': (('view_consulta_serasa_only', 'Pode visualizar apenas consulta Serasa'),), 'verbose_name_plural': 'Comprovantes Clientes'},
        ),
    ]
