# Generated by Django 4.2.16 on 2025-09-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0121_add_view_consulta_serasa_only_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprovantescliente',
            options={'permissions': (('view_consulta_serasa', 'Pode visualizar consulta Serasa'),), 'verbose_name_plural': 'Comprovantes Clientes'},
        ),
    ]
