# Generated by Django 4.2.16 on 2025-09-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0122_update_view_consulta_serasa_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='entrada_caixa_diaria',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='inscricao_estadual',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='meta_vendas_diaria',
        ),
    ]
