# Generated by Django 4.2.16 on 2025-11-07 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0125_pagamento_mais_prazo_pagamento_sem_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='porcentagem_desconto_16',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='bo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='devolucao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='flag_atrasado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='lembrete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='roubo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='sem_conexao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='numero_parcelas',
            field=models.CharField(choices=[('4', '4x'), ('6', '6x'), ('8', '8x'), ('10', '10x'), ('12', '12x'), ('14', '14x'), ('16', '16x')], max_length=20),
        ),
        migrations.CreateModel(
            name='StatusPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('cor_hex', models.CharField(default='#6c757d', max_length=7)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loja', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Status de Pagamentos',
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='pagamentos', to='vendas.statuspagamento'),
        ),
    ]
