# Generated by Django 4.2.16 on 2026-01-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0128_update_due_dates_to_01_16'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='analise_online',
            field=models.BooleanField(default=False, verbose_name='Análise Online'),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='data_pagamento',
            field=models.CharField(blank=True, choices=[('1', 'Dia 1'), ('16', 'Dia 16')], max_length=20, null=True, verbose_name='Data de pagamento'),
        ),
    ]
