# Generated by Django 4.2.16 on 2026-01-19 21:06

from django.db import migrations, models
import vendas.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0129_analisecreditocliente_analise_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='documento_assinado',
            field=models.FileField(blank=True, null=True, upload_to=vendas.models.upload_to_venda),
        ),
        migrations.AddField(
            model_name='venda',
            name='foto_cliente',
            field=models.ImageField(blank=True, null=True, upload_to=vendas.models.upload_to_venda),
        ),
    ]
