# Generated by Django 4.2.16 on 2026-03-04 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0130_venda_documento_assinado_venda_foto_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditocliente',
            name='entrada_informada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de entrada definido pelo operador. Deve ser >= entrada mínima do produto.', max_digits=10, null=True, verbose_name='Entrada informada'),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='data_pagamento',
            field=models.CharField(blank=True, choices=[('1', 'Dia 1'), ('10', 'Dia 10'), ('20', 'Dia 20')], max_length=20, null=True, verbose_name='Data de pagamento'),
        ),
        migrations.AlterField(
            model_name='analisecreditocliente',
            name='numero_parcelas',
            field=models.CharField(max_length=20, verbose_name='Número de parcelas'),
        ),
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('qtd_vezes', models.IntegerField(unique=True, verbose_name='Quantidade de parcelas')),
                ('porcentagem_juros', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem de juros (%)')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_loja', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcelamento',
                'verbose_name_plural': 'Parcelamentos',
                'ordering': ['qtd_vezes'],
            },
        ),
    ]
