# Generated by Django 4.2.16 on 2025-05-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasse',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
