# Generated by Django 4.2.16 on 2025-05-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_repasse_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repasse',
            name='funcionario',
        ),
    ]
