# Generated by Django 4.2.16 on 2025-05-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_remove_repasse_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repasse',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
