# Generated by Django 4.2.16 on 2025-05-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0022_alter_repasse_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repasse',
            options={'ordering': ['-data'], 'verbose_name': 'Repasse', 'verbose_name_plural': 'Repasse'},
        ),
    ]
